stages:
  - deploy

deploy_to_production:
  stage: deploy
  image: alpine:3.15
  only:
    - main
  before_script:
    # Установка ssh-клиента
    - apk add --no-cache openssh-client
    # Инициализация ssh-agent
    - eval $(ssh-agent -s)
    
    # --- ДИАГНОСТИКА КЛЮЧА ---
    - echo "Длина переменной SSH_PRIVATE_KEY составляет ${#SSH_PRIVATE_KEY} символов."
    - |
      if [ -f "$SSH_PRIVATE_KEY" ]; then
        echo "Обнаружен FILE-тип переменной. Путь к файлу: $SSH_PRIVATE_KEY"
        echo "Размер файла:" && ls -lh "$SSH_PRIVATE_KEY"
        echo "Первая строка файла:" && head -n 1 "$SSH_PRIVATE_KEY"
        echo "Последняя строка файла:" && tail -n 1 "$SSH_PRIVATE_KEY"
        # Копируем содержимое файла в id_rsa
        mkdir -p ~/.ssh && chmod 700 ~/.ssh
        cat "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
      else
        echo "Обнаружен STRING-тип переменной."
        echo "Первая строка переменной:" && echo "$SSH_PRIVATE_KEY" | head -n 1
        echo "Последняя строка переменной:" && echo "$SSH_PRIVATE_KEY" | tail -n 1
        # Записываем значение в id_rsa
        mkdir -p ~/.ssh && chmod 700 ~/.ssh
        echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
      fi
    # -------------------------

    - chmod 600 ~/.ssh/id_rsa
    # Добавляем ключ в агент
    - ssh-add ~/.ssh/id_rsa
    # Добавляем хост в известные
    - ssh-keyscan -H "$SERVER_IP" >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    # Подключение к VPS и выполнение команд обновления
    - |
      ssh root@$SERVER_IP "
        if [ -d '/root/mega' ]; then
          cd /root/mega
        else
          cd /root/planner-park
        fi
        
        # Обновляем URL репозитория на случай перехода на GitLab
        git remote set-url origin https://gitlab.com/hp-tools/mega.git || true
        
        # Стягиваем изменения
        git pull origin main
        
        # Пересобираем и перезапускаем проект в Docker-контейнере
        docker compose up -d --build || docker-compose up -d --build
      "
